### ISSUE TITLE
error 401 when running the example 

### ISSUE THREAD

**Issue by cccnrc** [saphetor/varsome-api-client-python#12]
Trying to run the example I got this error:

```
(venv) lab-cccnrc 13:04:51 >  varsome_api_run.py -g hg19 -q 'chr7-140453136-A-T' -p add-all-data=1

Traceback (most recent call last):
  File "/Users/cccnrc/Applications/varsome/venv/lib/python3.7/site-packages/varsome_api/client.py", line 87, in _make_request
    r.raise_for_status()
  File "/Users/cccnrc/Applications/varsome/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.varsome.com/lookup/chr7-140453136-A-T/hg19?add-all-data=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cccnrc/Applications/varsome/venv/bin/varsome_api_run.py", line 127, in <module>
    annotate_variant(sys.argv[1:])
  File "/Users/cccnrc/Applications/varsome/venv/bin/varsome_api_run.py", line 70, in annotate_variant
    result = api.lookup(query[0], params=request_parameters, ref_genome=ref_genome)
  File "/Users/cccnrc/Applications/varsome/venv/lib/python3.7/site-packages/varsome_api/client.py", line 154, in lookup
    return self.get(url, params=params)
  File "/Users/cccnrc/Applications/varsome/venv/lib/python3.7/site-packages/varsome_api/client.py", line 105, in get
    response = self._make_request(path, "GET", params=params)
  File "/Users/cccnrc/Applications/varsome/venv/lib/python3.7/site-packages/varsome_api/client.py", line 95, in _make_request
    raise VarSomeAPIException(response.status_code, error_message)
varsome_api.client.VarSomeAPIException: 401 (Authentication credentials were not provided.)
```

**Comment by ckopanos** [comment]
Hi, 
There have been changes in the API recently not yet reflected to the python client and its documentation. 
Access to the API requires authentication now. You can ask for an authentication token for a free / test plan by mailing support@saphetor.com

Sorry for the inconvenience.
