### ISSUE TITLE
How could I input chr2:83300000:106000000:dup to get result In Varsome api?

### ISSUE THREAD

**Issue by Luosanmu** [saphetor/varsome-api-client-python#24]
Hi,

I have a problem about Varsome api in Linux use Like this

Varsome api support to find this format cnv? or What is correct input method ?

thanks!

``
(varsome) [luohaosen@P-01 Varsome_test]$ varsome_api_run.py -u https://stable-api.varsome.com -q chr2%3A83300000%3A106000000%3Adup -g hg19 -p add-all-data=1 expand-pubmed-articles=0 -o ./test.json
Traceback (most recent call last):
  File "/ifs1/home/luohaosen/software/anaconda3/envs/varsome/lib/python3.9/site-packages/varsome_api/client.py", line 104, in _make_request
    r.raise_for_status()
  File "/ifs1/home/luohaosen/software/anaconda3/envs/varsome/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://stable-api.varsome.com/lookup/chr2%3A83300000%3A106000000%3Adup/hg19?add-all-data=1&expand-pubmed-articles=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ifs1/home/luohaosen/software/anaconda3/envs/varsome/bin/varsome_api_run.py", line 190, in <module>
    annotate_variant()
  File "/ifs1/home/luohaosen/software/anaconda3/envs/varsome/bin/varsome_api_run.py", line 110, in annotate_variant
    result = api.lookup(
  File "/ifs1/home/luohaosen/software/anaconda3/envs/varsome/lib/python3.9/site-packages/varsome_api/client.py", line 183, in lookup
    return self.get(url, params=params)
  File "/ifs1/home/luohaosen/software/anaconda3/envs/varsome/lib/python3.9/site-packages/varsome_api/client.py", line 124, in get
    response = self._make_request(path, "GET", params=params)
  File "/ifs1/home/luohaosen/software/anaconda3/envs/varsome/lib/python3.9/site-packages/varsome_api/client.py", line 112, in _make_request
    raise VarSomeAPIException(response.status_code, error_message)
varsome_api.client.VarSomeAPIException: 404 (Not found)
``

**Comment by kchatzikok** [comment]
Hi @Luosanmu,

since the variant you want to query is a cnv you should change the -q parameter to start with /cnv. The following works:
`./varsome_api_run.py -g hg19 -u https://stable-api.varsome.com -q 'cnv/chr2:83300000:106000000:dup' -p add-all-data=1`

We'll also update the README to include an example for cnv.
